version: '3'
services:
  nodejs:
    container_name: nodejs
    build:
      context: ./
      dockerfile: ./docker/Dockerfile
      args:
        USER_UID: ${USER_UID}
        USER_GID: ${USER_GID}
    ports:
      - "3001:3001"